[book]
authors = ["lambdaclass"]
language = "en"
src = "docs"
title = "ethlambda"
description = "Minimalist, fast and modular implementation of the Lean Ethereum client written in Rust"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/lambdaclass/ethlambda"
edit-url-template = "https://github.com/lambdaclass/ethlambda/edit/main/{path}"
# Make sections collapsible, starting fully expanded
fold = { enable = true, level = 1 }

# Broken-link checker
# https://github.com/marxin/mdbook-linkcheck2
# Needs to be installed with `cargo install mdbook-linkcheck2`
[output.linkcheck2]
optional = true
