[package]
name = "ethlambda-crypto"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
blst = "0.3.16"
ethlambda-metrics.workspace = true
ethlambda-types.workspace = true
rayon.workspace = true

leanvm.workspace = true
postcard.workspace = true

thiserror.workspace = true
tracing.workspace = true

[features]
shadow-integration = []

[dev-dependencies]
hex.workspace = true
zk_alloc.workspace = true
