[package]
name = "ethlambda-crypto"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ethlambda-types.workspace = true

xmss.workspace = true
lean-multisig.workspace = true
ssz.workspace = true
postcard.workspace = true

thiserror.workspace = true
rand.workspace = true
tracing.workspace = true

[features]
shadow-integration = []

[dev-dependencies]
hex.workspace = true
ssz.workspace = true
